### ISSUE TITLE
Make output independent from absolute date

### ISSUE THREAD

**Issue by joulev** [AY2223S2-CS2113-T15-4/tp#60]
Output may display relative dates like "in 2 days" or "5 days ago". Then the same input will give the same output regardless of when the program is run.

Output should not display absolute dates like "29 March 2023", because the output depends on the time the program is run, making testing difficult. That's the reason why there has been a lot of failing tests lately.

https://github.com/AY2223S2-CS2113-T15-4/tp/blob/c4d068258329792cf0018d6383fb4206eba458db/src/main/java/com/clanki/commands/UpdateCommand.java#L24

**Comment by joulev** [comment]
@javienneyeo Fix this first and foremost before anything else.

**Comment by SongZijin** [comment]
close with #127
