### ISSUE TITLE
[PE-D][Tester D] Invalid bye command exit program

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-4/tp#66]
**Description:** 
Invalid bye command should not allow users to exit from the program. But invalid bye command is not detected and cause users to exit from program. 

**Reproduce:**
1. Launch program
2. Input command `bye test`

**Expected outcome:**
Invalid command should be detected.

**Actual outcome:**
Invalid command is not detected and users exit the program.

**Screenshot:**
![image.png](https://raw.githubusercontent.com/wenxin-c/ped/main/files/6519a2f0-979d-4085-b07e-a4e074651f88.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: wenxin-c/ped#1

**Comment by joulev** [comment]
This is by design.
