### ISSUE TITLE
[PE-D][Tester A] Bug when putting answer as 你好， it would instead only show as ??

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-4/tp#67]
![image.png](https://raw.githubusercontent.com/SSzeWen/ped/main/files/61355438-c440-4ba5-a2f4-3d8a853e2792.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: SSzeWen/ped#3

**Comment by joulev** [comment]
This is because of limitations of Windows cmd.exe.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/44609036/229263205-66937043-68f4-4580-962b-02256edd8407.png">
