### ISSUE TITLE
[PE-D][Tester A] command in UG  shows INDEX [/q NEW_QUESTION] [/a NEW_ANSWER] [/d NEW_DUE_DATE], showing that all brackets are optional but typing index alone has no function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T15-4/tp#75]
![image.png](https://raw.githubusercontent.com/SSzeWen/ped/main/files/e770d6f3-9c3f-44a9-89a2-98a583295e0e.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: SSzeWen/ped#6

**Comment by SongZijin** [comment]
close with #127
