### ISSUE TITLE
[PE-D][Tester A] Delete functionality does not work

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-4/tp#77]
![image.png](https://raw.githubusercontent.com/SSzeWen/ped/main/files/da12aa57-b577-41a6-b9f6-794254ef0a3b.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: SSzeWen/ped#7

**Comment by moseslee9012** [comment]
Reformatted delete function according to UG
