### ISSUE TITLE
[PE-D][Tester A] Adding additional description will still cause add function to run

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-4/tp#79]
![image.png](https://raw.githubusercontent.com/SSzeWen/ped/main/files/7e667475-c5fc-42b6-a1e8-f896af5de1b1.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: SSzeWen/ped#8

**Comment by joulev** [comment]
Similar to #66.
