### ISSUE TITLE
[PE-D][Tester A] Updating to a very early date is allowed

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-4/tp#93]
![image.png](https://raw.githubusercontent.com/SSzeWen/ped/main/files/d10e1fed-2fc0-4029-b523-be45c913da3d.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: SSzeWen/ped#12

**Comment by joulev** [comment]
Yes because technically you can have a card that is due 20 years ago.
